mysql-connect:
  username: 'root'
  password: '^52]pt*xz+g^03_C#YHb'

  ipv4: '127.0.0.1'
  port: '3306'
  db-name: 'xfw'

cqhttp-ws-connect:
  ipv4: '127.0.0.1'
  port: '6700'
  secret: 'CQHTTP_SECRET'

poem-file-path: '../share/poem'

group-enable-send-randomgck:
  - 832158553
  - 821663521

user-black-list:
  - 873524616
